### ISSUE TITLE
Bytecode support?

### ISSUE THREAD

**Issue by SturdyPose** [ocaml/flexdll#149]
Is there bytecode support for flexdll? I'm using ctypes + foreign archives stanza which I assume is using flexdll in the background. Native compilation works just fine but whenever I want to run utop or compiled bytecode, I get this error:
```
Fatal error: cannot load shared library dllfoo
Reason: The specified module could not be found.
```
dllfoo.dll is copied to _build/default/lib/foo directory.

I can share more info if bytecode should be supported.

**Comment by SturdyPose** [comment]
Or if I type `dune utop` I get:
```
No master relocation table
Fatal error: cannot load shared library dllglad_stubs
Reason: Cannot resolve gladLoadGL
```

**Comment by dra27** [comment]
The first error looks like you are trying to run bytecode in either a misconfigured environment or where the DLLs are compiled but not installed. Or the stubs rely on a C library which doesn't have its runtime DLLs in PATH correctly (that's less likely if native code is working). Are you trying to run a binary from with `_build` rather than via `dune exec` or some such?

For the second issue, that looks like utop is not being compiled correctly by `dune utop`.

For both of these things, flexdll shouldn't be being the issue - flexdll is a loader, so it doesn't care about bytecode/native (from a technical perspective, flexlink happens to be written in OCaml and the project was conceived for OCaml's use, but it's got nothing else to do with it beyond that).

Sorry not to be able to be of much more help at the moment, although hopefully the knowledge that this isn't a flexdll issue can allow you to push it back towards utop/Dune!

**Comment by SturdyPose** [comment]
Thanks for the response! Seems really like it's dune issue. I've done manual compilation with linking using makefile and both bytecode and native work just fine + utop. Closing! :)

**Comment by SturdyPose** [comment]
@dra27 Found where the issue was and writing it down here for future searches.

I forgot to link part of the library for my dll and bytecode builds are running off dynamic libs whereas native ones can use archives. That's why bytecode wasn't running correctly and native one was.

I changed from `ar` tool to `ocamlmklib`
